# Generated by Django 6.0.3 on 2026-03-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="连接名称"
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("sqlite3", "SQLite"),
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                        ],
                        default="sqlite3",
                        max_length=20,
                        verbose_name="数据库类型",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        help_text="SQLite可留空",
                        max_length=200,
                        verbose_name="主机地址",
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True,
                        help_text="SQLite可留空",
                        null=True,
                        verbose_name="端口",
                    ),
                ),
                (
                    "database",
                    models.CharField(
                        help_text="SQLite为文件路径",
                        max_length=100,
                        verbose_name="数据库名",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="SQLite可留空",
                        max_length=100,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="SQLite可留空",
                        max_length=200,
                        verbose_name="密码",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "数据库连接",
                "verbose_name_plural": "数据库连接管理",
                "ordering": ["-created_at"],
            },
        ),
    ]
