# Generated by Django 6.0.3 on 2026-03-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_connections", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="databaseconnection",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "数据库连接",
                "verbose_name_plural": "数据库连接",
            },
        ),
        migrations.AlterField(
            model_name="databaseconnection",
            name="database",
            field=models.CharField(max_length=255, verbose_name="数据库名/文件路径"),
        ),
        migrations.AlterField(
            model_name="databaseconnection",
            name="host",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="主机地址"
            ),
        ),
        migrations.AlterField(
            model_name="databaseconnection",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="databaseconnection",
            name="password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="密码"
            ),
        ),
        migrations.AlterField(
            model_name="databaseconnection",
            name="port",
            field=models.IntegerField(blank=True, null=True, verbose_name="端口"),
        ),
        migrations.AlterField(
            model_name="databaseconnection",
            name="username",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="用户名"
            ),
        ),
    ]
