# Generated by Django 6.0.3 on 2026-03-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("items_count", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
