# Generated by Django 6.0.3 on 2026-03-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.PositiveIntegerField(unique=True)),
                ("date", models.DateField()),
                ("item_name", models.CharField(max_length=100)),
                ("item_type", models.CharField(max_length=50)),
                ("item_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_type", models.CharField(blank=True, max_length=20)),
                ("received_by", models.CharField(max_length=10)),
                ("time_of_sale", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["-date", "-order_id"],
            },
        ),
    ]
